public class BAD_ConfigurationPathException {
    // Vulnerability: Including sensitive file paths or configuration details in error messages generated by the application.

    public static void loadConfiguration(String configPath) {
        try {
            // Simulated attempt to load a configuration file
            throw new Exception("Failed to load configuration from " + configPath);
        } catch (Exception e) {
            // Insecure: Error message includes the full path to the configuration file, revealing potentially sensitive system information.
            System.err.println("Error: " + e.getMessage());
        }
    }

    public static void main(String[] args) {
        loadConfiguration("/etc/myapp/config.properties");
    }
}
