import java.util.logging.Logger;
import java.util.logging.Level;

public class BAD_ConfigurationPathException {
    private static final Logger LOGGER = Logger.getLogger(BAD_ConfigurationPathException.class.getName());
    // Deliberately insecure example: Including sensitive file paths or configuration details in error messages generated by the application.

    public static void loadConfiguration(String configPath) {
        try {
            // Simulated attempt to load a configuration file
            throw new Exception("Failed to load configuration from " + configPath);
        } catch (Exception e) {
            // Insecure: Directly logging the exception with the sensitive file path.
            LOGGER.log(Level.SEVERE, "Error: " + e.getMessage(), e);
        }
    }

    public static void main(String[] args) {
        loadConfiguration("/etc/myapp/config.properties");
    }
}
